# Generated by Django 5.2.6 on 2026-04-18 21:12

from decimal import Decimal

import django.db.models.deletion
import django.db.models.expressions
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("carts", "0007_alter_cartitem_unique_cart_product"),
        ("catalog", "0022_product_final_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated date"
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("assembling", "Assembling"),
                            ("shipped", "Shipped"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="order status",
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("courier", "Courier"), ("pickup", "Pickup")],
                        max_length=20,
                        verbose_name="delivery method",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="delivery address",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("on_delivery", "On delivery"),
                        ],
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="comment"),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        max_length=255, verbose_name="recipient name"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        max_length=255, verbose_name="recipient email"
                    ),
                ),
                (
                    "recipient_phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="+7__________",
                        max_length=128,
                        region="RU",
                        verbose_name="recipient phone number",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        help_text="Calculated by the system.",
                        max_digits=10,
                        verbose_name="total price",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        help_text="ORD-0000-000000",
                        max_length=20,
                        unique=True,
                        verbose_name="number",
                    ),
                ),
                (
                    "cart",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order",
                        to="carts.cart",
                        verbose_name="cart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
                "db_table": "orders_order",
                "db_table_comment": "Table containing orders.",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="created date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="updated date"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=8,
                        verbose_name="quantity",
                    ),
                ),
                (
                    "product_name_snapshot",
                    models.CharField(
                        max_length=255, verbose_name="product name snapshot"
                    ),
                ),
                (
                    "price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="price snapshot",
                    ),
                ),
                (
                    "total_price",
                    models.GeneratedField(
                        db_persist=True,
                        expression=models.ExpressionWrapper(
                            expression=django.db.models.expressions.CombinedExpression(
                                models.F("price_snapshot"),
                                "*",
                                models.F("quantity"),
                            ),
                            output_field=models.DecimalField(
                                decimal_places=2, max_digits=10
                            ),
                        ),
                        help_text="Calculated by the system.",
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=10
                        ),
                        verbose_name="total price",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "order item",
                "verbose_name_plural": "order items",
                "db_table": "orders_order_item",
                "db_table_comment": "Table containing order items.",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("order", "product"),
                        name="unique_order_product",
                        violation_error_message="This product is already in order.",
                    )
                ],
            },
        ),
    ]
