# Generated by Django 5.2.6 on 2025-12-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="accounts_user",
        ),
    ]
