# Generated by Django 5.2.6 on 2026-04-02 22:24

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="+7__________",
                max_length=128,
                null=True,
                region="RU",
                unique=True,
                verbose_name="phone number",
            ),
        ),
    ]
