# Generated by Django 5.2.6 on 2026-04-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_managers_alter_user_phone_number"),
        ("social_django", "0017_usersocialauth_user_social_auth_uid_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyUserSocialAuth",
            fields=[],
            options={
                "verbose_name": "Social account",
                "verbose_name_plural": "Social accounts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("social_django.usersocialauth",),
        ),
    ]
