repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  -   id: check-yaml
  -   id: check-json
  -   id: check-toml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace
  -   id: check-merge-conflict
  -   id: check-case-conflict
  -   id: debug-statements
  -   id: detect-private-key

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort

- repo: https://github.com/pycqa/flake8
  rev: 7.3.0
  hooks:
    - id: flake8
      additional_dependencies:
        - flake8>=7.3.0
        - flake8-bandit>=4.1.1
        - flake8-bugbear>=24.12.12
        - flake8-docstrings>=1.7.0
        - flake8-eradicate>=1.5.0
        - flake8-quotes>=3.4.0
        - pep8-naming>=0.15.1

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: python mypy.py
      language: system
      types: [python]
      pass_filenames: false
      require_serial: true
