# Generated by Django 5.2.6 on 2025-10-30 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfessionalArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название профессиональной области",
                        max_length=255,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "профессиональная область",
                "verbose_name_plural": "профессиональные области",
                "db_table": "professional_areas",
                "db_table_comment": "Таблица с информацией о профессиональных областях",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название региона",
                        max_length=255,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "регион",
                "verbose_name_plural": "регионы",
                "db_table": "regions",
                "db_table_comment": "Таблица с информацией о регионах",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название города",
                        max_length=255,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        help_text="Регион, к которому относится город",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="vacancies.region",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "город",
                "verbose_name_plural": "города",
                "db_table": "cities",
                "db_table_comment": "Таблица с информацией о городах",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Заголовок вакансии",
                        max_length=255,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        help_text="Вступительный текст о вакансии (обычный текст)",
                        verbose_name="Краткое описание",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Подробное описание вакансии (HTML-разметка)",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "work_schedule",
                    models.CharField(
                        choices=[
                            ("full", "Полный день"),
                            ("shift", "Сменный график"),
                            ("flex", "Гибкий график"),
                            ("remote", "Удаленная работа"),
                        ],
                        default="full",
                        help_text="Предполагаемый режим работы",
                        max_length=10,
                        verbose_name="График работы",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("no_exp", "Без опыта"),
                            ("1_3", "От 1 года до 3 лет"),
                            ("3_6", "От 3 до 6 лет"),
                            ("6_plus", "Более 6 лет"),
                        ],
                        default="no_exp",
                        help_text="Требуемый для работы опыт",
                        max_length=10,
                        verbose_name="Опыт работы",
                    ),
                ),
                (
                    "salary_from",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Минимальная зарплата",
                        null=True,
                        verbose_name="Зарплата от",
                    ),
                ),
                (
                    "salary_to",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Максимальная зарплата",
                        null=True,
                        verbose_name="Зарплата до",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Определяет, активна ли вакансия",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Дата и время добавления вакансии",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Дата и время последнего обновления вакансии",
                        verbose_name="Дата обновления",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="Город и регион размещения вакансии",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="vacancies.city",
                        verbose_name="Город и регион",
                    ),
                ),
                (
                    "professional_area",
                    models.ForeignKey(
                        help_text="Профессиональная область вакансии",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="vacancies.professionalarea",
                        verbose_name="Профессиональная область",
                    ),
                ),
            ],
            options={
                "verbose_name": "вакансия",
                "verbose_name_plural": "вакансии",
                "db_table": "vacancies",
                "db_table_comment": "Таблица с информацией о вакансиях",
                "ordering": ("-created_at", "title"),
            },
        ),
    ]
