# Generated by Django 5.2.6 on 2025-11-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(
                help_text="Подробное описание вакансии (HTML-разметка, используйте div, ul, h3, li)",
                verbose_name="Описание",
            ),
        ),
    ]
