# Generated by Django 5.2.6 on 2025-11-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_alter_vacancy_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                help_text="Название города.",
                max_length=255,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Регион, к которому относится город.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="vacancies.region",
                verbose_name="регион",
            ),
        ),
        migrations.AlterField(
            model_name="professionalarea",
            name="name",
            field=models.CharField(
                help_text="Название профессиональной области.",
                max_length=255,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                help_text="Название региона.",
                max_length=255,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="city",
            field=models.ForeignKey(
                help_text="Город и регион размещения вакансии.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="vacancies.city",
                verbose_name="город и регион",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время добавления вакансии.",
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(
                help_text="Подробное описание вакансии (HTML-разметка, используйте div, ul, h3, li).",
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("no_exp", "Без опыта"),
                    ("1_3", "От 1 года до 3 лет"),
                    ("3_6", "От 3 до 6 лет"),
                    ("6_plus", "Более 6 лет"),
                ],
                default="no_exp",
                help_text="Требуемый для работы опыт.",
                max_length=10,
                verbose_name="опыт работы",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, активна ли вакансия.",
                verbose_name="активна",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="professional_area",
            field=models.ForeignKey(
                help_text="Профессиональная область вакансии.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="vacancies.professionalarea",
                verbose_name="профессиональная область",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_from",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Минимальная зарплата.",
                null=True,
                verbose_name="зарплата от",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_to",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Максимальная зарплата.",
                null=True,
                verbose_name="зарплата до",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="short_description",
            field=models.TextField(
                help_text="Вступительный текст о вакансии (обычный текст).",
                verbose_name="краткое описание",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title",
            field=models.CharField(
                help_text="Заголовок вакансии.",
                max_length=255,
                verbose_name="заголовок",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления вакансии.",
                verbose_name="дата обновления",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_schedule",
            field=models.CharField(
                choices=[
                    ("full", "Полный день"),
                    ("shift", "Сменный график"),
                    ("flex", "Гибкий график"),
                    ("remote", "Удаленная работа"),
                ],
                default="full",
                help_text="Предполагаемый режим работы.",
                max_length=10,
                verbose_name="график работы",
            ),
        ),
    ]
