# Generated by Django 5.2.6 on 2025-11-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_alter_city_name_alter_city_region_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="city",
            table="vacancies_city",
        ),
        migrations.AlterModelTable(
            name="professionalarea",
            table="vacancies_professional_area",
        ),
        migrations.AlterModelTable(
            name="region",
            table="vacancies_region",
        ),
        migrations.AlterModelTable(
            name="vacancy",
            table="vacancies_vacancy",
        ),
    ]
