# Generated by Django 5.2.6 on 2025-11-13 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vacancies",
            "0004_alter_city_table_alter_professionalarea_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ("-created_at", "title"),
                "verbose_name": "vacancy",
                "verbose_name_plural": "vacancies",
            },
        ),
        migrations.AlterModelTableComment(
            name="vacancy",
            table_comment="Table containing job vacancies.",
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="city",
            field=models.ForeignKey(
                help_text="City and region where the vacancy is posted.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="vacancies.city",
                verbose_name="city and region",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time when the vacancy was added.",
                verbose_name="created date",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the vacancy (HTML markup, use div, ul, h3, li).",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="experience_level",
            field=models.CharField(
                choices=[
                    ("no_exp", "No experience"),
                    ("1_3", "From 1 to 3 years"),
                    ("3_6", "From 3 to 6 years"),
                    ("6_plus", "More than 6 years"),
                ],
                default="no_exp",
                help_text="Required work experience level.",
                max_length=10,
                verbose_name="experience level",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Determines whether the vacancy is visible.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="professional_area",
            field=models.ForeignKey(
                help_text="Professional field of the vacancy.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="vacancies.professionalarea",
                verbose_name="professional area",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_from",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum salary.",
                null=True,
                verbose_name="salary from",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_to",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Maximum salary.",
                null=True,
                verbose_name="salary to",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="short_description",
            field=models.TextField(
                help_text="Brief introductory text about the vacancy.",
                verbose_name="short description",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title",
            field=models.CharField(
                help_text="Vacancy title.",
                max_length=255,
                verbose_name="title",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the vacancy was last updated.",
                verbose_name="updated date",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_schedule",
            field=models.CharField(
                choices=[
                    ("full", "Full-time"),
                    ("shift", "Shift schedule"),
                    ("flex", "Flexible schedule"),
                    ("remote", "Remote work"),
                ],
                default="full",
                help_text="Expected work schedule.",
                max_length=10,
                verbose_name="work schedule",
            ),
        ),
    ]
