# Generated by Django 5.2.6 on 2025-11-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vacancies",
            "0005_alter_vacancy_options_alter_vacancy_table_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professionalarea",
            options={
                "ordering": ("name",),
                "verbose_name": "professional area",
                "verbose_name_plural": "professional areas",
            },
        ),
        migrations.AlterModelTableComment(
            name="professionalarea",
            table_comment="Table containing professional areas.",
        ),
        migrations.AlterField(
            model_name="professionalarea",
            name="name",
            field=models.CharField(
                help_text="Professional area name.",
                max_length=255,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
