# Generated by Django 5.2.6 on 2025-11-13 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0006_alter_professionalarea_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ("name",),
                "verbose_name": "city",
                "verbose_name_plural": "cities",
            },
        ),
        migrations.AlterModelTableComment(
            name="city",
            table_comment="Table containing cities.",
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                help_text="City name.",
                max_length=255,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Region to which the city belongs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="vacancies.region",
                verbose_name="region",
            ),
        ),
    ]
