# Generated by Django 5.2.6 on 2025-11-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vacancies",
            "0007_alter_city_options_alter_city_table_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "ordering": ("name",),
                "verbose_name": "region",
                "verbose_name_plural": "regions",
            },
        ),
        migrations.AlterModelTableComment(
            name="region",
            table_comment="Table containing regions.",
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                help_text="Region name.",
                max_length=255,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
