# Generated by Django 5.2.6 on 2025-11-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vacancies",
            "0008_alter_region_options_alter_region_table_comment_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="name_en",
            field=models.CharField(
                help_text="City name.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="city",
            name="name_ru",
            field=models.CharField(
                help_text="City name.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="professionalarea",
            name="name_en",
            field=models.CharField(
                help_text="Professional area name.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="professionalarea",
            name="name_ru",
            field=models.CharField(
                help_text="Professional area name.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="name_en",
            field=models.CharField(
                help_text="Region name.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="name_ru",
            field=models.CharField(
                help_text="Region name.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="description_en",
            field=models.TextField(
                help_text="Detailed description of the vacancy (HTML markup, use div, ul, h3, li).",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="description_ru",
            field=models.TextField(
                help_text="Detailed description of the vacancy (HTML markup, use div, ul, h3, li).",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="short_description_en",
            field=models.TextField(
                help_text="Brief introductory text about the vacancy.",
                null=True,
                verbose_name="short description",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="short_description_ru",
            field=models.TextField(
                help_text="Brief introductory text about the vacancy.",
                null=True,
                verbose_name="short description",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="title_en",
            field=models.CharField(
                help_text="Vacancy title.",
                max_length=255,
                null=True,
                verbose_name="title",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="title_ru",
            field=models.CharField(
                help_text="Vacancy title.",
                max_length=255,
                null=True,
                verbose_name="title",
            ),
        ),
    ]
