# Generated by Django 5.2.6 on 2026-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "vacancies",
            "0009_city_name_en_city_name_ru_professionalarea_name_en_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="experience_level",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="work_experience",
            field=models.CharField(
                choices=[
                    ("no_exp", "No experience"),
                    ("1_3", "From 1 to 3 years"),
                    ("3_6", "From 3 to 6 years"),
                    ("6_plus", "More than 6 years"),
                ],
                default="no_exp",
                help_text="Required work experience.",
                max_length=10,
                verbose_name="work experience",
            ),
        ),
    ]
