# Generated by Django 5.2.6 on 2026-03-07 15:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0010_remove_vacancy_experience_level_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="vacancy",
            table_comment="Table containing vacancies.",
        ),
        migrations.AddField(
            model_name="city",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AddField(
            model_name="professionalarea",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="professionalarea",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="vacancies.region",
                verbose_name="region",
            ),
        ),
        migrations.AlterField(
            model_name="professionalarea",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="professionalarea",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="professionalarea",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vacancies",
                to="vacancies.city",
                verbose_name="city",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="created date"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(
                help_text="Text or HTML markup: div, ul, h3, li.",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description_en",
            field=models.TextField(
                help_text="Text or HTML markup: div, ul, h3, li.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description_ru",
            field=models.TextField(
                help_text="Text or HTML markup: div, ul, h3, li.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="professional_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vacancies",
                to="vacancies.professionalarea",
                verbose_name="professional area",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_from",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="salary from"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary_to",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="salary to"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="short_description",
            field=models.TextField(verbose_name="short description"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="short_description_en",
            field=models.TextField(
                null=True, verbose_name="short description"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="short_description_ru",
            field=models.TextField(
                null=True, verbose_name="short description"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="title_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_experience",
            field=models.CharField(
                choices=[
                    ("no_exp", "No experience"),
                    ("1_3", "From 1 to 3 years"),
                    ("3_6", "From 3 to 6 years"),
                    ("6_plus", "More than 6 years"),
                ],
                default="no_exp",
                max_length=10,
                verbose_name="work experience",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="work_schedule",
            field=models.CharField(
                choices=[
                    ("full", "Full-time"),
                    ("shift", "Shift schedule"),
                    ("flex", "Flexible schedule"),
                    ("remote", "Remote work"),
                ],
                default="full",
                max_length=10,
                verbose_name="work schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="vacancy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("salary_from__isnull", True),
                    ("salary_to__isnull", True),
                    ("salary_from__lt", models.F("salary_to")),
                    _connector="OR",
                ),
                name="check_vacancy_salary_from_lt_salary_to",
                violation_error_message="Maximum salary must be greater than minimum salary.",
            ),
        ),
    ]
