# Generated by Django 5.2.6 on 2025-12-24 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0014_category_alt_text_category_alt_text_en_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cart_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("converted", "Сonverted"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="active",
                        help_text="Current cart status (active, converted, abandoned).",
                        max_length=20,
                        verbose_name="cart status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time the cart was created.",
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the cart was last updated.",
                        verbose_name="updated date",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user to which the cart belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
                "db_table": "carts_cart",
                "db_table_comment": "Table containing carts.",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of products in cart item.",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "price_snapshot",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the product at the time it was added to the cart.",
                        max_digits=10,
                        verbose_name="price snapshot",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="The cart to which the cart item belongs.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="carts.cart",
                        verbose_name="cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product belonging to the cart item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="catalog.product",
                        verbose_name="product",
                    ),
                ),
            ],
            options={
                "verbose_name": "cart item",
                "verbose_name_plural": "cart items",
                "db_table": "carts_cart_item",
                "db_table_comment": "Table containing cart items.",
            },
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cart_status", "active")),
                fields=("user",),
                name="unique_active_cart_user",
                violation_error_message="A user can have only one active cart.",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"), name="unique_cart_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="constraint_quantity_gt_zero",
            ),
        ),
    ]
