# Generated by Django 5.2.6 on 2026-03-08 13:57

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cartitem_total_price"),
        ("catalog", "0017_remove_productattribute_attribute_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={
                "ordering": ("-updated_at",),
                "verbose_name": "cart",
                "verbose_name_plural": "carts",
            },
        ),
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "cart item",
                "verbose_name_plural": "cart items",
            },
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="constraint_quantity_gt_zero",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="cart_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("converted", "Сonverted"),
                    ("abandoned", "Abandoned"),
                ],
                default="active",
                max_length=20,
                verbose_name="cart status",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="created date"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="carts.cart",
                verbose_name="cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="price_snapshot",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="price snapshot"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="catalog.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="quantity"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="total_price",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.ExpressionWrapper(
                    expression=django.db.models.expressions.CombinedExpression(
                        models.F("price_snapshot"), "*", models.F("quantity")
                    ),
                    output_field=models.DecimalField(
                        decimal_places=2, max_digits=10
                    ),
                ),
                help_text="Calculated by the system.",
                output_field=models.DecimalField(
                    decimal_places=2, max_digits=10
                ),
                verbose_name="total price",
            ),
        ),
        migrations.AlterConstraint(
            model_name="cartitem",
            name="unique_cart_product",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"),
                name="unique_cart_product",
                violation_error_message="This product is already in your cart.",
            ),
        ),
    ]
