# Generated by Django 5.2.6 on 2026-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_alter_cart_options_alter_cartitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price_snapshot",
            field=models.DecimalField(
                decimal_places=2,
                editable=False,
                max_digits=10,
                verbose_name="price snapshot",
            ),
        ),
    ]
