# Generated by Django 5.2.6 on 2026-04-04 16:41

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_alter_cartitem_price_snapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=8,
                verbose_name="quantity",
            ),
        ),
    ]
