# Generated by Django 5.2.6 on 2026-04-04 16:42

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0005_remove_cartitem_total_price_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="total_price",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.ExpressionWrapper(
                    expression=django.db.models.expressions.CombinedExpression(
                        models.F("price_snapshot"), "*", models.F("quantity")
                    ),
                    output_field=models.DecimalField(
                        decimal_places=2, max_digits=10
                    ),
                ),
                help_text="Calculated by the system.",
                output_field=models.DecimalField(
                    decimal_places=2, max_digits=10
                ),
                verbose_name="total price",
            ),
        ),
    ]
