# Generated by Django 5.2.6 on 2026-04-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0006_cartitem_total_price"),
        ("catalog", "0022_product_final_price"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="cartitem",
            name="unique_cart_product",
            constraint=models.UniqueConstraint(
                fields=("cart", "product"),
                name="unique_cart_product",
                violation_error_message="This product is already in cart.",
            ),
        ),
    ]
