# Generated by Django 5.2.6 on 2025-10-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={
                "ordering": ("name",),
                "verbose_name": "атрибут",
                "verbose_name_plural": "атрибуты",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("sort_order", "name"),
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AlterModelOptions(
            name="productattribute",
            options={
                "verbose_name": "атрибут продукта",
                "verbose_name_plural": "атрибуты продуктов",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ("product__name", "sort_order"),
                "verbose_name": "изображение продукта",
                "verbose_name_plural": "изображения продукта",
            },
        ),
        migrations.AlterModelOptions(
            name="productnutrition",
            options={
                "ordering": ("product__name",),
                "verbose_name": "пищевая ценность",
                "verbose_name_plural": "пищевая ценность",
            },
        ),
    ]
