# Generated by Django 5.2.6 on 2025-10-18 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0002_alter_attribute_options_alter_category_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text="Продукт, к которому относится изображение",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="catalog.product",
                verbose_name="Продукт",
            ),
        ),
    ]
