# Generated by Django 5.2.6 on 2025-11-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_options_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(
                help_text="Название атрибута (например: вес, срок хранения, условия хранения).",
                max_length=255,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время добавления категории.",
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Описание категории.",
                verbose_name="описание",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, показывается ли категория в каталоге.",
                verbose_name="активна",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Название категории.",
                max_length=255,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Родительская категория (если есть вложенность).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="catalog.category",
                verbose_name="родительская категория",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Уникальное имя для URL (латиница, дефисы).",
                max_length=255,
                unique=True,
                verbose_name="URL-идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок сортировки категорий в списке.",
                verbose_name="порядок отображения",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления категории.",
                verbose_name="дата обновления",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="Категория, к которой относится продукт.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition",
            field=models.TextField(
                help_text="Состав продукта.", verbose_name="состав"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время добавления продукта.",
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Описание продукта.", verbose_name="описание"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Скидка на продукт в процентах.",
                max_digits=5,
                verbose_name="скидка (%)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Определяет, показывается ли продукт в каталоге.",
                verbose_name="активен",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Название продукта.",
                max_length=255,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Цена продукта.",
                max_digits=10,
                verbose_name="цена",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                help_text="Артикул (Stock Keeping Unit).",
                max_length=100,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество продуктов на складе.",
                verbose_name="остаток",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_type",
            field=models.CharField(
                choices=[("kg", "кг"), ("l", "л"), ("pcs", "шт")],
                default="pcs",
                help_text="Единица измерения продукта (например: кг, л, шт).",
                max_length=10,
                verbose_name="единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления продукта.",
                verbose_name="дата обновления",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="attribute",
            field=models.ForeignKey(
                help_text="Атрибут продукта (например: вес, срок хранения, условия хранения).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_values",
                to="catalog.attribute",
                verbose_name="атрибут",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                help_text="Продукт, к которому относится атрибут.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="catalog.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="value",
            field=models.CharField(
                help_text="Значение атрибута (например: 500 г, 12 месяцев).",
                max_length=255,
                verbose_name="значение",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Описание изображения для SEO и доступности.",
                max_length=255,
                verbose_name="альтернативный текст",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_path",
            field=models.ImageField(
                help_text="Путь к изображению продукта.",
                upload_to="product_images/",
                verbose_name="изображение",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text="Продукт, к которому относится изображение.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="catalog.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Порядок сортировки изображений продукта.",
                verbose_name="порядок отображения",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Калории (ккал).",
                max_digits=6,
                null=True,
                verbose_name="калории",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="carbs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Углеводы (г).",
                max_digits=6,
                null=True,
                verbose_name="углеводы",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="fats",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Жиры (г).",
                max_digits=6,
                null=True,
                verbose_name="жиры",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="product",
            field=models.OneToOneField(
                help_text="Продукт, к которому относится данная пищевая ценность.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_nutrition",
                to="catalog.product",
                verbose_name="продукт",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="proteins",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Белки (г).",
                max_digits=6,
                null=True,
                verbose_name="белки",
            ),
        ),
    ]
