# Generated by Django 5.2.6 on 2025-11-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0005_alter_attribute_name_alter_category_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attribute",
            table="catalog_attribute",
        ),
        migrations.AlterModelTable(
            name="category",
            table="catalog_category",
        ),
        migrations.AlterModelTable(
            name="product",
            table="catalog_product",
        ),
        migrations.AlterModelTable(
            name="productattribute",
            table="catalog_product_attribute",
        ),
        migrations.AlterModelTable(
            name="productimage",
            table="catalog_product_image",
        ),
        migrations.AlterModelTable(
            name="productnutrition",
            table="catalog_product_nutrition",
        ),
    ]
