# Generated by Django 5.2.6 on 2025-11-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0006_alter_attribute_table_alter_category_table_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-created_at", "name"),
                "verbose_name": "product",
                "verbose_name_plural": "products",
            },
        ),
        migrations.AlterModelTableComment(
            name="product",
            table_comment="Table containing product information.",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                help_text="The category to which the product belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition",
            field=models.TextField(
                help_text="Product composition.", verbose_name="composition"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time the product was added.",
                verbose_name="created date",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                help_text="Product description.", verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Product discount in percent.",
                max_digits=5,
                verbose_name="discount",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Determines whether the product is displayed in the catalog.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Product name.", max_length=255, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Product price.",
                max_digits=10,
                verbose_name="price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                help_text="Stock Keeping Unit (SKU).",
                max_length=100,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                help_text="Unique URL identifier (letters, numbers, hyphens).",
                max_length=255,
                unique=True,
                verbose_name="URL-identifier",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of products in stock.",
                verbose_name="stock",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_type",
            field=models.CharField(
                choices=[("kg", "kg"), ("l", "L"), ("pcs", "pcs")],
                default="pcs",
                help_text="Unit of measurement of the product (e.g., kg, l, pcs).",
                max_length=10,
                verbose_name="unit type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the product was last updated.",
                verbose_name="updated date",
            ),
        ),
    ]
