# Generated by Django 5.2.6 on 2025-11-11 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0007_alter_product_options_alter_product_table_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productnutrition",
            options={
                "ordering": ("product__name",),
                "verbose_name": "nutritional value",
                "verbose_name_plural": "nutritional values",
            },
        ),
        migrations.AlterModelTableComment(
            name="productnutrition",
            table_comment="Table containing nutritional values of products.",
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="calories",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Calories (kcal).",
                max_digits=6,
                null=True,
                verbose_name="calories",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="carbs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Carbs (g).",
                max_digits=6,
                null=True,
                verbose_name="carbs",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="fats",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fats (g).",
                max_digits=6,
                null=True,
                verbose_name="fats",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="product",
            field=models.OneToOneField(
                help_text="The product to which the nutritional value belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_nutrition",
                to="catalog.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="proteins",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Proteins (g).",
                max_digits=6,
                null=True,
                verbose_name="proteins",
            ),
        ),
    ]
