# Generated by Django 5.2.6 on 2025-11-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_productnutrition_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attribute",
            options={
                "ordering": ("name",),
                "verbose_name": "attribute",
                "verbose_name_plural": "attributes",
            },
        ),
        migrations.AlterModelTableComment(
            name="attribute",
            table_comment="Table containing possible product attributes.",
        ),
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(
                help_text="Name of the attribute (e.g., weight, shelf life, storage conditions).",
                max_length=255,
                unique=True,
                verbose_name="name",
            ),
        ),
    ]
