# Generated by Django 5.2.6 on 2025-11-11 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_attribute_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productattribute",
            options={
                "verbose_name": "product attribute",
                "verbose_name_plural": "product attributes",
            },
        ),
        migrations.AlterModelTableComment(
            name="productattribute",
            table_comment="Table containing product attribute values.",
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="attribute",
            field=models.ForeignKey(
                help_text="The product attribute (e.g., weight, shelf life, storage conditions).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_values",
                to="catalog.attribute",
                verbose_name="attribute",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                help_text="The product to which the attribute belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="catalog.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="value",
            field=models.CharField(
                help_text="The specific value of the attribute (e.g., 500 g, 12 months).",
                max_length=255,
                verbose_name="value",
            ),
        ),
    ]
