# Generated by Django 5.2.6 on 2025-11-11 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_productattribute_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("sort_order", "name"),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelTableComment(
            name="category",
            table_comment="Table containing product categories.",
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and time the category was added.",
                verbose_name="created date",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Category description.",
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Determines whether the category is displayed in the catalog.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Category name.",
                max_length=255,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category (if nesting is used).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="catalog.category",
                verbose_name="parent category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Unique URL identifier (letters, numbers, hyphens).",
                max_length=255,
                unique=True,
                verbose_name="URL-identifier",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order in which categories appear in lists.",
                verbose_name="display order",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the category was last updated.",
                verbose_name="updated date",
            ),
        ),
    ]
