# Generated by Django 5.2.6 on 2025-11-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0011_alter_category_options_alter_category_table_comment_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ("product__name", "sort_order"),
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
            },
        ),
        migrations.AlterModelTableComment(
            name="productimage",
            table_comment="Table containing product images.",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Description of the image for SEO and accessibility.",
                max_length=255,
                verbose_name="alternative text",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_path",
            field=models.ImageField(
                help_text="Path to the product image.",
                upload_to="product_images/",
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text="The product to which the image belongs.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="catalog.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order in which product images appear in lists.",
                verbose_name="display order",
            ),
        ),
    ]
