# Generated by Django 5.2.6 on 2025-11-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="name_en",
            field=models.CharField(
                help_text="Name of the attribute (e.g., weight, shelf life, storage conditions).",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="name_ru",
            field=models.CharField(
                help_text="Name of the attribute (e.g., weight, shelf life, storage conditions).",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Category description.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description_ru",
            field=models.TextField(
                blank=True,
                help_text="Category description.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                help_text="Category name.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                help_text="Category name.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="composition_en",
            field=models.TextField(
                help_text="Product composition.",
                null=True,
                verbose_name="composition",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="composition_ru",
            field=models.TextField(
                help_text="Product composition.",
                null=True,
                verbose_name="composition",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(
                help_text="Product description.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(
                help_text="Product description.",
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                help_text="Product name.",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                help_text="Product name.",
                max_length=255,
                null=True,
                verbose_name="name",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_en",
            field=models.CharField(
                help_text="The specific value of the attribute (e.g., 500 g, 12 months).",
                max_length=255,
                null=True,
                verbose_name="value",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_ru",
            field=models.CharField(
                help_text="The specific value of the attribute (e.g., 500 g, 12 months).",
                max_length=255,
                null=True,
                verbose_name="value",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text_en",
            field=models.CharField(
                blank=True,
                help_text="Description of the image for SEO and accessibility.",
                max_length=255,
                null=True,
                verbose_name="alternative text",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="alt_text_ru",
            field=models.CharField(
                blank=True,
                help_text="Description of the image for SEO and accessibility.",
                max_length=255,
                null=True,
                verbose_name="alternative text",
            ),
        ),
    ]
