# Generated by Django 5.2.6 on 2025-11-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_attribute_name_en_attribute_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="alt_text",
            field=models.CharField(
                blank=True,
                help_text="Description of the image for SEO and accessibility.",
                max_length=255,
                verbose_name="alternative text",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="alt_text_en",
            field=models.CharField(
                blank=True,
                help_text="Description of the image for SEO and accessibility.",
                max_length=255,
                null=True,
                verbose_name="alternative text",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="alt_text_ru",
            field=models.CharField(
                blank=True,
                help_text="Description of the image for SEO and accessibility.",
                max_length=255,
                null=True,
                verbose_name="alternative text",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image_path",
            field=models.ImageField(
                blank=True,
                help_text="Path to the category image.",
                null=True,
                upload_to="category_images/",
                verbose_name="image",
            ),
        ),
    ]
