# Generated by Django 5.2.6 on 2026-02-09 14:08

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_category_alt_text_category_alt_text_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="final_price",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.ExpressionWrapper(
                    expression=django.db.models.expressions.CombinedExpression(
                        models.F("price"),
                        "*",
                        django.db.models.expressions.CombinedExpression(
                            models.Value(1),
                            "-",
                            django.db.models.expressions.CombinedExpression(
                                models.F("discount"), "/", models.Value(100.0)
                            ),
                        ),
                    ),
                    output_field=models.DecimalField(
                        decimal_places=2, max_digits=10
                    ),
                ),
                help_text="Product final price (autocalculated).",
                output_field=models.DecimalField(
                    decimal_places=2, max_digits=10
                ),
                verbose_name="final price",
            ),
        ),
    ]
