# Generated by Django 5.2.6 on 2026-03-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_product_final_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(is_active=True, stock__gt=0, then=True),
                    default=False,
                    output_field=models.BooleanField(),
                ),
                help_text="Product availability (autocalculated).",
                output_field=models.BooleanField(),
                verbose_name="availability",
            ),
        ),
    ]
