# Generated by Django 5.2.6 on 2026-03-08 08:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_product_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="attribute",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="productnutrition",
            options={
                "ordering": ("product__name",),
                "verbose_name": "product nutrition",
                "verbose_name_plural": "product nutritions",
            },
        ),
        migrations.AlterModelTableComment(
            name="product",
            table_comment="Table containing products.",
        ),
        migrations.AlterModelTableComment(
            name="productnutrition",
            table_comment="Table containing product nutritions",
        ),
        migrations.RemoveField(
            model_name="category",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="category",
            name="alt_text_en",
        ),
        migrations.RemoveField(
            model_name="category",
            name="alt_text_ru",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_path",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="alt_text_en",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="alt_text_ru",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="image_path",
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=False,
                null=True,
                quality=80,
                scale=None,
                size=(1024, 1024),
                upload_to="category_images/",
                verbose_name="image",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="attributes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="attributes"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="attributes_en",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="attributes"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="attributes_ru",
            field=models.JSONField(
                blank=True, default=dict, null=True, verbose_name="attributes"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default=1,
                force_format="WEBP",
                keep_meta=False,
                quality=80,
                scale=None,
                size=(1024, 1024),
                upload_to="product_images/",
                verbose_name="image",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productimage",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AddField(
            model_name="productnutrition",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productnutrition",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="created date"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, unique=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="catalog.category",
                verbose_name="parent",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="sort order"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="catalog.category",
                verbose_name="category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition",
            field=models.TextField(verbose_name="composition"),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition_en",
            field=models.TextField(null=True, verbose_name="composition"),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition_ru",
            field=models.TextField(null=True, verbose_name="composition"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="created date"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="discount",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="final_price",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.ExpressionWrapper(
                    expression=django.db.models.expressions.CombinedExpression(
                        models.F("price"),
                        "*",
                        django.db.models.expressions.CombinedExpression(
                            models.Value(1),
                            "-",
                            django.db.models.expressions.CombinedExpression(
                                models.F("discount"), "/", models.Value(100.0)
                            ),
                        ),
                    ),
                    output_field=models.DecimalField(
                        decimal_places=2, max_digits=10
                    ),
                ),
                help_text="Calculated by the system.",
                output_field=models.DecimalField(
                    decimal_places=2, max_digits=10
                ),
                verbose_name="final price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_available",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(is_active=True, stock__gt=0, then=True),
                    default=False,
                    output_field=models.BooleanField(),
                ),
                help_text="Calculated by the system.",
                output_field=models.BooleanField(),
                verbose_name="availability",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                max_length=255, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0, verbose_name="stock"),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_type",
            field=models.CharField(
                choices=[("kg", "kg"), ("l", "L"), ("pcs", "pcs")],
                default="pcs",
                max_length=10,
                verbose_name="unit type",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="updated date"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="sort order"
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="calories",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="calories",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="carbs",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="carbs"
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="fats",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=6, verbose_name="fats"
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition",
                to="catalog.product",
                verbose_name="product",
            ),
        ),
        migrations.AlterField(
            model_name="productnutrition",
            name="proteins",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                verbose_name="proteins",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["attributes"], name="index_product_attributes_gin"
            ),
        ),
        migrations.DeleteModel(
            name="Attribute",
        ),
        migrations.DeleteModel(
            name="ProductAttribute",
        ),
    ]
