# Generated by Django 5.2.6 on 2026-04-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_remove_productattribute_attribute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="composition",
            field=models.TextField(
                blank=True, max_length=255, verbose_name="composition"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition_en",
            field=models.TextField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="composition",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="composition_ru",
            field=models.TextField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="composition",
            ),
        ),
    ]
