# Generated by Django 5.2.6 on 2026-04-04 16:01

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_alter_product_composition_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_available",
        ),
        migrations.AddField(
            model_name="product",
            name="weight_step",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Step for weighing products.",
                max_digits=4,
                null=True,
                verbose_name="weight step",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=8,
                verbose_name="stock",
            ),
        ),
    ]
