# Generated by Django 5.2.6 on 2026-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0019_remove_product_is_available_product_weight_step_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(is_active=True, stock__gt=0, then=True),
                    default=False,
                    output_field=models.BooleanField(),
                ),
                help_text="Calculated by the system.",
                output_field=models.BooleanField(),
                verbose_name="availability",
            ),
        ),
    ]
