# Generated by Django 5.2.6 on 2026-04-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_product_is_available"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="final_price",
        ),
    ]
