# Generated by Django 5.2.6 on 2026-04-09 07:43

from decimal import Decimal

import django.db.models.expressions
import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_remove_product_final_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="final_price",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.ExpressionWrapper(
                    expression=django.db.models.expressions.CombinedExpression(
                        django.db.models.functions.math.Floor(
                            django.db.models.expressions.CombinedExpression(
                                models.F(name="price"),
                                "*",
                                django.db.models.expressions.CombinedExpression(
                                    models.Value(value=1),
                                    "-",
                                    django.db.models.expressions.CombinedExpression(
                                        models.F(name="discount"),
                                        "/",
                                        models.Value(value=100.0),
                                    ),
                                ),
                            )
                        ),
                        "+",
                        models.Value(value=Decimal("0.99")),
                    ),
                    output_field=models.DecimalField(
                        decimal_places=2, max_digits=10
                    ),
                ),
                help_text="Calculated by the system.",
                output_field=models.DecimalField(
                    decimal_places=2, max_digits=10
                ),
                verbose_name="final price",
            ),
        ),
    ]
