# Generated by Django 5.2.6 on 2026-04-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_product_final_price"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)),
                name="check_product_stock_non_negative",
            ),
        ),
    ]
