# Generated by Django 5.2.6 on 2026-04-22 03:48

from decimal import Decimal

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_product_check_product_stock_non_negative"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_available",
        ),
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        is_active=True,
                        stock__gte=django.db.models.functions.comparison.Coalesce(
                            models.F("weight_step"), models.Value(Decimal("1"))
                        ),
                        then=True,
                    ),
                    default=False,
                    output_field=models.BooleanField(),
                ),
                help_text="Calculated by the system.",
                output_field=models.BooleanField(),
                verbose_name="availability",
            ),
        ),
    ]
